[package]
name = "game_bevy"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.14"
bevy_atmosphere = "0.10.0"
bevy_flycam = "*"
multiarray = "0.1.3"
noise = "0.9.0"
pixelate_mesh = "0.4.0"
rand = "0.8.5"
